version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./src/:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
